//
//  CBNetworkType.swift
//  CityBike
//
//  Created by Tomasz Szulc on 04/06/15.
//  Copyright (c) 2015 Tomasz Szulc. All rights reserved.
//

import Foundation

enum CBNetworkType: String {
    case Alba = "alba"
    case Andria = "andria"
    case Arbike = "arbike"
    case AscoliPiceno = "ascoli-piceno"
    case Austin = "austin"
    
    case BarclaysCycleHire = "barclays-cycle-hire"
    case Bariinbici = "bariinbici"
    case Bassanodelgrappa = "bassanodelgrappa"
    case BayAreaBikeShare = "bay-area-bike-share"
    case Bbbike = "bbbike"
    case BemowoBike = "bemowo-bike"
    case BianzoneInBici = "bianzone-in-bici"
    case Biciamo = "biciamo"
    case BiciCo = "bici-co"
    case BiciInBusto = "bici-in-busto"
    case Bicikelj = "bicikelj"
    case Bicileon = "bicileon"
    case Bicing = "bicing"
    case Bicinquartucciu = "bicinquartucciu"
    case Bicipalma = "bicipalma"
    case BiciPerugia = "bici-perugia"
    case Bicischio = "bicischio"
    case Bicloo = "bicloo"
    case Biella = "biella"
    case Bigi = "bigi"
    case Bikebh = "bikebh"
    case Bikebrasilia = "bikebrasilia"
    case BikeChattanooga = "bike-chattanooga"
    case BikeInBath = "bike-in-bath"
    case Bikemi = "bikemi"
    case Bikepetrolina = "bikepetrolina"
    case Bikepoa = "bikepoa"
    case Bikesalvador = "bikesalvador"
    case Bikesampa = "bikesampa"
    case Bikesantos = "bikesantos"
    case BikeSharingNapoli = "bike-sharing-napoli"
    case Bikesorocaba = "bikesorocaba"
    case BikerBialystok = "biker-bialystok"
    case Bikerecife = "bikerecife"
    case Bikerio = "bikerio"
    case BikesSRM = "bikes-srm"
    case BixiMontreal = "bixi-montreal"
    case BixiToronto = "bixi-toronto"
    case Bizi = "bizi"
    case Boulder = "boulder"
    case Bra = "bra"
    case Brindisi = "brindisi"
    case Broward = "broward"
    case Bubi = "bubi"
    case BublrBikes = "bublr-bikes"
    case BysykkelLillestrom = "bysykkel-lillestrom"

    case Cagliari = "cagliari"
    case CallabikeBerlin = "callabike-berlin"
    case CallabikeDarmstadt = "callabike-darmstadt"
    case CallabikeFrankfurt = "callabike-frankfurt"
    case CallabikeFrankfurtAirport = "callabike-frankfurt-airport"
    case CallabikeKoln = "callabike-koln"
    case CallabikeLuneburg = "callabike-luneburg"
    case CallabikeMarburg = "callabike-marburg"
    case CallabikeMunchen = "callabike-munchen"
    case CallabikeRusselsheim = "callabike-russelsheim"
    case CallabikeStuttgart = "callabike-stuttgart"
    case CallabikeWiesbaden = "callabike-wiesbaden"
    case CapitalBikeshare = "capital-bikeshare"
    case Carbonia = "carbonia"
    case Casalmaggiore = "casalmaggiore"
    case CassanoDAdda = "cassano-d-adda"
    case Castellucchio = "castellucchio"
    case Catbike = "catbike"
    case Charlotte = "charlotte"
    case Chivasso = "chivasso"
    case Ciclopi = "ciclopi"
    case Ciclosampa = "ciclosampa"
    case CityByBike = "city-by-bike"
    case CitiBikeNyc = "citi-bike-nyc"
    case CitybikeWien = "citybike-wien"
    case Citycycle = "citycycle"
    case Civitavecchia = "civitavecchia"
    case Cogo = "cogo"
    case ColumbiaCounty = "columbia-county"
    case Cristolib = "cristolib"
    case Cuneo = "cuneo"
    case Cyclic = "cyclic"
    
    case DecobikeMiamiBeach = "decobike-miami-beach"
    case DecobikeLongBeach = "decobike-long-beach"
    case DecobikeSanDiego = "decobike-san-diego"
    case Denver = "denver"
    case Desmoines = "desmoines"
    case Divvy = "divvy"
    case Dkvelo = "dkvelo"
    case Dublinbikes = "dublinbikes"
    
    case EasybikeDidymoteicho = "easybike-didymoteicho"
    case EasybikeDrapetsona = "easybike-drapetsona"
    case EasybikeIoannina = "easybike-ioannina"
    case EasybikeIrakleio = "easybike-irakleio"
    case EasybikeKarditsa = "easybike-karditsa"
    case EasybikeKavala = "easybike-kavala"
    case EasybikeKomotini = "easybike-komotini"
    case EasybikeMani = "easybike-mani"
    case EasybikeNafpaktos = "easybike-nafpaktos"
    case EasybikeNicosia = "easybike-nicosia"
    case Ecobici = "ecobici"
    case EMotionTrento = "e-motion-trento"
    case EMotionPergineValsugana = "e-motion-pergine-valsugana"
    case EMotionrovereto = "e-motion-rovereto"
    case Enna = "enna"
    
    case Fortworth = "fortworth"
    case Fossano = "fossano"
    case FreeBikeSharing = "free-bike-sharing"
    
    case GimmeBike = "gimme-bike"
    case Girocleta = "girocleta"
    case Gobike = "gobike"
    case Goeteborg = "goeteborg"
    case Goodbike = "goodbike"
    case Greenbikeslc = "greenbikeslc"
    case Greenville = "greenville"
    
    case Hawaii = "hawaii"
    case Houston = "houston"
    case Hubway = "hubway"
    
    case Idecycle = "idecycle"
    case IndianaPacersBikeshare = "indiana-pacers-bikeshare"
    
    case Jesinbici = "jesinbici"
    
    case Kansascity = "kansascity"
    case KmkBike = "kmk-bike"
    case Konrad = "konrad"
    case KonstancinskiRowerMiejski = "konstancinski-rower-miejski"
    case KvbRad = "kvb-rad"
    
    case Lecce = "lecce"
    case Lecco = "lecco"
    case LeVelo = "le-velo"
    case LiBiaVelo = "li-bia-velo"
    case Longanoinbici = "longanoinbici"
    
    case Madison = "madison"
    case ManerbaInBici = "manerba-in-bici"
    case Mantova = "mantova"
    case MarEBici = "mar-e-bici"
    case MeglioInBici = "meglio-in-bici"
    case MelbourneBikeShare = "melbourne-bike-share"
    case Mobike = "mobike"
    case MonopoliBike = "monopoli-bike"
    
    case Nashville = "nashville"
    case Nbici = "nbici"
    case NiceRide = "nice-ride"
    case Notoinbici = "notoinbici"
    case Noviligure = "noviligure"
    case Novara = "novara"
    
    case Oderzo = "oderzo"
    case OlbiaBike = "olbia-bike"
    case Omaha = "omaha"
    case OnrollAlbacete = "onroll-albacete"
    case OnrollAlhamaDeMurcia = "onroll-alhama-de-murcia"
    case OnrollAlmunecar = "onroll-almunecar"
    case OnrollAntequera = "onroll-antequera"
    case OnrollAranjuez = "onroll-aranjuez"
    case OnrollArandaDeDuero = "onroll-aranda-de-duero"
    case OnrollARua = "onroll-a-rua"
    case OnrollBadajoz = "onroll-badajoz"
    case OnrollBaeza = "onroll-baeza"
    case OnrollBenidorm = "onroll-benidorm"
    case OnrollBlanca = "onroll-blanca"
    case OnrollCieza = "onroll-cieza"
    case OnrollCiudadReal = "onroll-ciudad-real"
    case OnrollDonBenitoVillanueva = "onroll-don-benito-villanueva"
    case OnrollElCampello = "onroll-el-campello"
    case OnrollElche = "onroll-elche"
    case OnrollGuadalajara = "onroll-guadalajara"
    case OnrollJaen = "onroll-jaen"
    case OnrollLalin = "onroll-lalin"
    case OnrollLasPalmas = "onroll-las-palmas"
    case OnrollMontilla = "onroll-montilla"
    case OnrollMula = "onroll-mula"
    case OnrollNovelda = "onroll-novelda"
    case OnrollOBarco = "onroll-o-barco"
    case OnrollPaiporta = "onroll-paiporta"
    case OnrollPalencia = "onroll-palencia"
    case OnrollPinto = "onroll-pinto"
    case OnrollPriegoDeCordoba = "onroll-priego-de-cordoba"
    case OnrollPuertollano = "onroll-puertollano"
    case OnrollPuertoLumbreras = "onroll-puerto-lumbreras"
    case OnrollRedondela = "onroll-redondela"
    case OnrollSalamanca = "onroll-salamanca"
    case OnrollSanJavier = "onroll-san-javier"
    case OnrollSanPedro = "onroll-san-pedro"
    case OnrollSantJoan = "onroll-sant-joan"
    case OnrollSegovia = "onroll-segovia"
    case OnrollSoria = "onroll-soria"
    case OnrollTalavera = "onroll-talavera"
    case OnrollUbeda = "onroll-ubeda"
    case OnrollUniversidadDeGranada = "onroll-universidad-de-granada"
    case OnrollViaVerde = "onroll-via-verde"
    case OnrollVillaquilambre = "onroll-villaquilambre"
    case OnrollVinaros = "onroll-vinaros"
    case OpoleBike = "opole-bike"
    case Ossola = "ossola"
    
    case Parkinbici = "parkinbici"
    case Parma = "parma"
    case PaviaInBici = "pavia-in-bici"
    case Piacenza = "piacenza"
    case Pinerolo = "pinerolo"
    case Pistoiainbici = "pistoiainbici"
    case Pontedera = "pontedera"
    case Pordenone = "pordenone"
    case PortofinoParkAndBike = "portofino-park-and-bike"
    case PoznanskiRowerMiejski = "poznanski-rower-miejski"
    case PrataCamportaccio = "prata-camportaccio"
    case Prato = "prato"

    case RapidCity = "rapid-city"
    case ReggioEmilia = "reggio-emilia"
    case Rietinbici = "rietinbici"
    case Rimini = "rimini"
    case RomaNBike = "roma-n-bike"
    case RowerTrojmiejski = "rower-trojmiejski"

    case Saluzzo = "saluzzo"
    case SanAntonio = "sanantonio"
    case Sandonadipiave = "sandonadipiave"
    case Santiago = "santiago"
    case Savigliano = "savigliano"
    case Savona = "savona"
    case ScegliInBici = "scegli-in-bici"
    case Sellero = "sellero"
    case Settimotorinese = "settimotorinese"
    case Sevici = "sevici"
    case Sondrio = "sondrio"
    case Spartanburg = "spartanburg"
    case Speziainbici = "speziainbici"
    case Stadtrad = "stadtrad"
    case StockholmCyclocity = "stockholm-cyclocity"

    case Terni = "terni"
    case Thessbike = "thessbike"
    case Tigullionbike = "tigullionbike"
    case TiranoInBici = "tirano-in-bici"
    case ToBike = "to-bike"
    case ToyamaCyclocity = "toyama-cyclocity"
    case Tradate = "tradate"
    case Treviso = "treviso"
    case Tusbic = "tusbic"

    case Udine = "udine"
    case Ugento = "ugento"
    case Ustica = "ustica"
    
    case Velam = "velam"
    case Valenbisi = "valenbisi"
    case Velib = "velib"
    case Velik = "velik"
    case VelIn = "vel-in"
    case Velo = "velo"
    case Velo2 = "velo2"
    case VeloAntwerpen = "velo-antwerpen"
    case Velobleu = "velobleu"
    case Velocea = "velocea"
    case VelociteBesancon = "velocite-besancon"
    case VelociteMulhouse = "velocite-mulhouse"
    case Veloh = "veloh"
    case Velostanlib = "velostanlib"
    case Velov = "velov"
    case Venezia = "venezia"
    case Vercelli = "vercelli"
    case Veturilo = "veturilo"
    case Villo = "villo"
    case Villorba = "villorba"
    case VilniusCyclocity = "vilnius-cyclocity"
    case Vlille = "vlille"

    case WeCycle = "we-cycle"
    case WeLoveBike = "we-love-bike"
    case WroclawskiRowerMiejski = "wroclawski-rower-miejski"
}