language: objective-c

branches:
  only:
    - master

xcode_project: Swifternalization.xcodeproj
xcode_scheme: SwifternalizationTests
osx_image: beta-xcode6.3
xcode_sdk: iphonesimulator8.3 

script:
- xcodebuild test -project Swifternalization.xcodeproj -scheme SwifternalizationTests